### PR TITLE
Update vyatta-interfaces-dataplane-v1.yang

### PR DESCRIPTION
**Pull request by pimvanpelt**
Allow for MTU set to industry standard of 9216 bytes.
Fixes DAN-285.

### CODE REVIEW

**Review by pimvanpelt — COMMENTED** [review]
Verified to work end to end including through `vyatta-interfaces.pl` and netlink `ip`:

```
pim@ddln1# set interfaces dataplane dp0p5s0f1 mtu 9216
[edit]
pim@ddln1# commit

pim@ddln1:~$ ip link show dp0p5s0f1
12: dp0p5s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9216 qdisc fq_codel state UP mode DORMANT group default qlen 1000
    link/ether 9c:69:b4:61:64:0d brd ff:ff:ff:ff:ff:ff
    alias Core: ddln0

pim@ddln1:~$ show protocols ospf neighbor 
Neighbor ID     Pri State           Dead Time Address         Interface                        RXmtL RqstL DBsmL
194.1.163.5       1 Full/DROther      33.892s 194.1.163.12    dp0p5s0f1:194.1.163.13               0     0     0

pim@ddln1:~$ show protocols ospfv3 neighbor 
Neighbor ID     Pri    DeadTime    State/IfState         Duration I/F[State]
194.1.163.5       1    00:00:36     Full/PointToPoint    00:22:48 dp0p5s0f1[PointToPoint]
```

And packets are forwarded up through 9216 bytes:

```
pim@ddln1:~$ ping 194.1.163.12 mtu-discovery do size 9188
PING 194.1.163.12 (194.1.163.12) 9188(9216) bytes of data.
9196 bytes from 194.1.163.12: icmp_seq=1 ttl=64 time=0.927 ms
9196 bytes from 194.1.163.12: icmp_seq=2 ttl=64 time=0.864 ms
^C
--- 194.1.163.12 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 2ms
rtt min/avg/max/mdev = 0.864/0.895/0.927/0.043 ms

pim@ddln1:~$ ping 194.1.163.12 mtu-discovery do size 9189
PING 194.1.163.12 (194.1.163.12) 9189(9217) bytes of data.
ping: local error: Message too long, mtu=9216
^C
--- 194.1.163.12 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

**Comment by srinivasknarayan** [comment]
Thanks for your contribution and the verification log. We will get this merged.

**Comment by pimvanpelt** [comment]
Gentle reminder to merge before next release.

**Comment by srinivasknarayan** [comment]
Hi Pim,
Yes - this will be merged soon. Thanks for the reminder.

**Comment by pimvanpelt** [comment]
Another two months have passed - can you help me understand what's blocking this?

**Comment by srinivasknarayan** [comment]
Apologies for the delay. This has now been merged. I will decline this PR. The code will appear in the next release.

https://github.com/danos/vyatta-cfg-dataplane/commit/87064e3e919acce855cc618115ac624c93c0f890

**Comment by pimvanpelt** [comment]
okidoki, thanks for getting back to me and for merging.

**Pull request closed without merging**
